/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const SlateReact_DefaultElement: typeof import('slate-react')['DefaultElement']
  const SlateReact_DefaultLeaf: typeof import('slate-react')['DefaultLeaf']
  const SlateReact_Editable: typeof import('slate-react')['Editable']
  const SlateReact_ReactEditor: typeof import('slate-react')['ReactEditor']
  const SlateReact_Slate: typeof import('slate-react')['Slate']
  const SlateReact_useFocused: typeof import('slate-react')['useFocused']
  const SlateReact_withReact: typeof import('slate-react')['withReact']
  const Slate_Editor: typeof import('slate')['Editor']
  const Slate_Element: typeof import('slate')['Element']
  const Slate_Location: typeof import('slate')['Location']
  const Slate_Node: typeof import('slate')['Node']
  const Slate_Path: typeof import('slate')['Path']
  const Slate_Point: typeof import('slate')['Point']
  const Slate_Range: typeof import('slate')['Range']
  const Slate_Transforms: typeof import('slate')['Transforms']
  const Slate_createEditor: typeof import('slate')['createEditor']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
